### ISSUE TITLE
arch linux 下运行遇到问题（1.8、11、17均未成功）

### ISSUE THREAD

**Issue by zcbxxx1** [P1nganD/Rookie#7]
![图片](https://github.com/P1nganD/Rookie/assets/56199489/70633c67-d7c2-484c-bac2-4dc9fff11669)

**Comment by P1nganD** [comment]
师傅java，8u65试试，高版本的java因为javafx的问题，8u65这个版本的java好用，漏洞也可以直接复现，大部分环境部署你也能复现

**Comment by zcbxxx1** [comment]
可以了，感谢师傅指点
